// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRKP-FuJbsvyHXJAGSrE40o6akhMUGQ8',
    appId: '1:432589541248:web:edb760639bc34c9696fb65',
    messagingSenderId: '432589541248',
    projectId: 'messenger-58be3',
    authDomain: 'messenger-58be3.firebaseapp.com',
    storageBucket: 'messenger-58be3.appspot.com',
    measurementId: 'G-E785NQE65K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2m5kq1Imsp7Tp1jh3CIG6gOnwsVy2Hw0',
    appId: '1:432589541248:android:5bf4da05e36f854a96fb65',
    messagingSenderId: '432589541248',
    projectId: 'messenger-58be3',
    storageBucket: 'messenger-58be3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_XG9wB7C0v5pkIo5NQheiDyUbP3nKFk',
    appId: '1:432589541248:ios:07b6d5440da4d3ce96fb65',
    messagingSenderId: '432589541248',
    projectId: 'messenger-58be3',
    storageBucket: 'messenger-58be3.appspot.com',
    iosBundleId: 'com.example.messangerTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_XG9wB7C0v5pkIo5NQheiDyUbP3nKFk',
    appId: '1:432589541248:ios:c7874daa3c89a55896fb65',
    messagingSenderId: '432589541248',
    projectId: 'messenger-58be3',
    storageBucket: 'messenger-58be3.appspot.com',
    iosBundleId: 'com.example.messangerTest.RunnerTests',
  );
}
